### PR TITLE
add NewSocketWithConn to construct socket using a custom net.PacketConn

### PR DESCRIPTION
**Pull request by raftario**
Adds a way to create a socket from a user provided PacketConn to support custom transports

### CODE REVIEW

**Comment by anacrolix** [comment]
What about making this an opt like with https://pkg.go.dev/github.com/anacrolix/go-libutp#WithLogger? I have another API where the number of constructors exploded with all the variants, this might be a way to preemptively stop that. Cheers

**Comment by anacrolix** [comment]
@raftario are you still interested/depend on this change?

**Comment by raftario** [comment]
No longer depend on it no, feel free to do as you wish with it

**Comment by anacrolix** [comment]
Okay, it makes sense to add this but I'll wait until someone else has the need.

**Pull request closed without merging**
