### PR TITLE
too many output of this error message

### PR DESCRIPTION
**Pull request by ucwong**

### CODE REVIEW

**Comment by anacrolix** [comment]
@ucwong what's the error message you're seeing? It might be better to lower the log level, and filter it out by default. Or add another special case.

**Comment by ucwong** [comment]
> @ucwong what's the error message you're seeing? It might be better to lower the log level, and filter it out by default. Or add another special case.

@anacrolix Yes, Debug or trace level should be OK for this log msg

**Comment by anacrolix** [comment]
Do you have the specific error message you're seeing by any chance? I will adjust this PR to log at a lower level.

**Comment by ucwong** [comment]
> Do you have the specific error message you're seeing by any chance? I will adjust this PR to log at a lower level.

Just this, thank you.

**Comment by anacrolix** [comment]
Merged in https://github.com/anacrolix/go-libutp/commit/895ca40a235fceb0caf7a40838270b9fbf0c5b96

**Pull request closed without merging**
